USB_VID = 0x239A
USB_PID = 0x809C
USB_PRODUCT = "Nucleo H755ZI CM4 - CPy"
USB_MANUFACTURER = "STMicroelectronics"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = H7
MCU_VARIANT = STM32H755xx
MCU_PACKAGE = LQFP144
MCU_CORE = CM4

LD_COMMON = boards/common_default.ld
LD_FILE = boards/STM32H755_cm4_fs.ld

CIRCUITPY_BLEIO = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BLE_FILE_SERVICE = 0
