USB_VID = 0x239A
USB_PID = 0x8098
USB_PRODUCT = "Nucleo H743ZI - CPy"
USB_MANUFACTURER = "STMicroelectronics"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = H7
MCU_VARIANT = STM32H755xx
MCU_PACKAGE = LQFP144

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32H755_fs.ld

CIRCUITPY_COUNTIO = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_ULAB = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_PIXELBUF = 0
CIRCUITPY_RANDOM = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_ROTARYIO = 0

CIRCUITPY_USB_MIDI = 0
CIRCUITPY_REQUIRE_I2C_PULLUPS = 0
CIRCUITPY_ULAB = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_USB_HID = 0