USB_VID = 0x239A
USB_PID = 0x809B
USB_PRODUCT = "Nucleo H755ZI CM7 - CPy"
USB_MANUFACTURER = "STMicroelectronics"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = H7
MCU_VARIANT = STM32H755xx
MCU_PACKAGE = LQFP144
MCU_CORE = CM7

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32H755_cm7_fs.ld
